config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
  resources :brands,except: [:show,:new,:create,:update,:destroy] do
    collection do
      get "brand_details"
      get "/:brand/:phone" => "brands#phone_details"
    end
    member do
      get "phone_details"
    end
  end
  resources :brands_data
  #get ':alias_name/:phone_alias_name' => "phones#show"
  #get ':alias_name' => "brands#show"
  get '/brands/:id' => "brands#brand_details"
  #get '/brands/:brand_name/:id' => "phones#phone_details"
  resources :phone_details
  resources :phones #,param: :alias_name
  resources :articles,path: 'blog'
end

app/models/brand.rb
class Brand < ApplicationRecord
	has_many :phones,dependent: :destroy
	#has_many :phones
	has_many :phone_details
	#has_attached_file :image, styles: { large: "500x500>", medium: "420x420>", thumb: "100x100>" }
	#validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
	has_attached_file :logo, styles: { thumb: "100x100>" }
	validates_attachment_content_type :logo, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

	
	def Brand.update_priority(brand_obj)
		#if brand_obj.priority_changed?
			all_brands = Brand.all
			lesser_priority = all_brands.collect{|t| t if t.priority < brand_obj.priority}.reject{|t| t.nil?}
			same_priority = all_brands.collect{|t| t if t.priority == brand_obj.priority}.reject{|t| t.nil?}
			bigger_priority = all_brands.collect{|t| t if t.priority > brand_obj.priority}.reject{|t| t.nil?}
			same_priority.each_with_index do |obj,index|
				if obj.id != brand_obj.id
					obj.update_attributes(priority: lesser_priority.size + 2)
				end
			end
			default_val = lesser_priority.size + 2 
			bigger_priority.each_with_index do |obj,index|
				obj.update_attributes(priority:  default_val + 1)
				default_val = default_val + 1
			end


			# all_brands.each_with_index do |brand,index|
			# 	if brand.priority < brand_obj.priority
			# 	elsif brand.priority == brand_obj.priority && brand.id != brand_obj.id
			# 		brand.update_attributes(priority: brand.priority + 1)
			# 	elsif brand.priority > brand_obj.priority
			# 		brand.update_attributes(priority: brand.priority + 1)
			# 	end
			# end
		#end
	end
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  before_action :set_brand, only: [:edit, :update, :destroy]

  def brand_details
    @brand = Brand.find_by(alias_name: params[:id]) #if params[:alias_name].present?
    #@brand = Brand.find(params[:id]) if params[:alias_name].blank?
    @phones = @brand.phones #.order("release_date DESC")
    @latest_releases = @phones #.order #("release_date ASC").limit(4)
  end

  def phone_details
    @phone = Phone.find_by(alias_name: params[:phone])
    @phone_detail = @phone.phone_detail

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_brand
      @brand = Brand.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def brand_params
      params.fetch(:brand).permit(:image,:logo,:name,:description,:alias_name,:priority)
    end
end

app/views/brands/_form.html.erb
<%#= @brand.inspect %>
<%= simple_form_for(@brand,class: "form-horizontal") do |f| %>
  <% if brand.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(brand.errors.count, "error") %> prohibited this brand from being saved:</h2>

      <ul>
      <% brand.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.input :name,input_html: {class: "form-control"}  %>
  </div>
  <!-- <div class="form-group">
    <%#= f.input :alias_name,input_html: {class: "form-control"}  %>
  </div> -->
  <div class="form-group">
    <%= f.input :description,input_html: {class: "form-control"}  %>
  </div>
  <div class="form-group">
    <%= f.input :priority,input_html: {class: "form-control"}  %>
  </div>
  <div class="form-group">
    <%= f.input :logo, as: :file %>
  </div>
  <div class="actions">
    <%= f.button :submit,"Submit",class: "btn btn-default" %>
  </div>
<% end %><br/>

app/views/brands/brand_details.html.erb
<div class="container">
	<div class="row">
		<div class="col-lg-12">
			<h1 class="page-header">
				<%= @latest_releases.first.name %>
				<small><%= " (" + @brand.name + " latest release "  + ")"%></small>
			</h1>
		</div>
	</div>
	<div class="row">
		<a href="<%= '/phones/'+ @latest_releases.first.name.gsub(" ","_") rescue nil%>">
			<div class="col-md-8">
				<%= image_tag(@latest_releases.first.avatar) %>
				<%#=  File.exists?(Rails.root.to_s+"/app/assets/images/750*500/#{@brand.name.downcase}.jpg") ? image_tag("/assets/750*500/#{@brand.name.downcase}.jpg",class: "img-responsive portfolio-item",:size => "750x500") : image_tag("/assets/750*500/default2.jpg",class: "img-responsive portfolio-item",:size => "750x500") rescue image_tag("/assets/750*500/default2.jpg",class: "img-responsive portfolio-item",:size => "750x500")%>
			</div>
		</a>
		<div class="col-md-4">
			<h3>Description</h3>
			<p>
				<%= @brand.description.present? ? @brand.description : "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae. Sed dui lorem, adipiscing in adipiscing et, interdum nec metus. Mauris ultricies, justo eu convallis placerat, felis enim." %>
			</p>
			<h3>Latest releases</h3>
			<ul>
				<% @latest_releases.each do |l_release| %>
					<li><%= l_release.name %></li>
				<% end %>
      </ul>
    </div>
  </div>
  <div class="row">
		<div class="col-lg-12">
    	<h3 class="page-header"><%= @brand.name + " Other Phones" %></h3>
    </div>
    <% @phones.each do |phone| %>
    	<div class="col-sm-3 col-xs-6">
    		<a href="<%= '/brands/'+ @brand.name.downcase + '/' +  phone.name.gsub(" ","_").downcase %>" style="text-align: center;">
    			<%= image_tag(phone.avatar) %>
    			<%#=  File.exists?(Rails.root.to_s+"/app/assets/images/420*420/#{phone.name.downcase}.jpg") ? image_tag("/assets/420*420/#{phone.name.downcase}.jpg",class: "img-responsive portfolio-item",:size => "420x420") : image_tag("/assets/420*420/default2.jpg",class: "img-responsive portfolio-item",:size => "420x420") rescue image_tag("/assets/420*420/default2.jpg",class: "img-responsive portfolio-item",:size => "420x420")%>
					<h2><strong><span style="display: inline-table;text-align: center;width:100%;"><%= phone.name %></span></strong></h2><br/>
    		</a>
			</div>
    <% end %>
  </div>
	<!-- Code by Milind -->
	<div class="row">
		<% @phones.each do |phone| %>
		<div class="col-sm-6 col-md-3" style="margin-top:30px;">
			<!-- <a href="<%#= '/'+ @brand.name.downcase + '/' +  phone.name.gsub(" ","_").downcase %>"> -->
				<!-- <div class="thumbnail">  -->
					<div class="phone_image">
					<%= phone.image.present? ? (image_tag(phone.image.url,class: "img-responsive",style: "height: 212px;")) : image_tag("default.jpg",style: "height: 212px; width: 100%; display: block;") rescue nil%>
					</div>
					<div class="phone_name_tag">
						<strong><%= phone.name %></strong>
					</div>
				<!-- </div>  -->
			<!-- </a> -->
		</div>
		<% end %>
	</div>
</div>

<!-- End of code -->

app/views/brands/edit.html.erb
<h1>Editing Brand</h1>

<%= render 'form', brand: @brand %>

<%= link_to 'Show', @brand %> |
<%= link_to 'Back', brands_path %>

app/views/brands/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Top Mobile Brands</h1>
<table class = "table table-striped">
  <thead>
    <tr>
      <th>Priority</th>
      <th>Name</th>
      <td>Logo</td>
      <th colspan="3"> Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @brands.each do |brand| %>
      <tr>
        <td><%= brand.priority  %></td>
        <td><b><%= link_to brand.name,brand %></b><%= brand.phones.length > 0 ? " (" + brand.phones.length.to_s + " Phones" + ")" : " (No phones available)" rescue nil%></td>
        <td><%= brand.logo_file_name.present? ? image_tag(brand.logo.url(:thumb)) : image_tag("default.jpg")  %></td>
        <td><%= link_to 'Show', brand %></td>
        <td><%= link_to 'Edit',edit_brand_path(brand.id) %></td>
        <td><%= link_to 'Destroy', brand, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<%= link_to 'New Brand', new_brand_path %>

app/views/brands/new.html.erb
<h1>New Brand</h1>

<%= render 'form', brand: @brand %>

<%= link_to 'Back', brands_path %>

app/views/brands/phone_details.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @phone_detail.phone.name + " Details" %></h1>

<table>
  <tr>
    <th>Name: &nbsp;</th>
    <td><%= @phone.name %></td>
  </tr>
  <tr>
    <th>Size: &nbsp;</th>
    <td><%= @phone_detail.display_size rescue "N/A"%></td>
  </tr>
  <tr>
    <th>Resolution: &nbsp;</th>
    <td><%= @phone_detail.display_resolution rescue "N/A"%></td>
  </tr>
  <tr></tr>
  <tr>
    <th>Display Type: &nbsp;</th>
    <td><%= @phone_detail.display_type rescue "N/A"%></td>
  </tr>

  <tr>
    <th>Multitouch: &nbsp;</th>
    <td><%= @phone_detail.display_multitouch rescue "N/A"%></td>
  </tr>
  <tr>
    <th>RAM: &nbsp;</th>
    <td><%= @phone_detail.ram rescue "N/A"%></td>
  </tr>
  <tr>
    <th>Chipset: &nbsp;</th>
    <td><%= @phone_detail.chipset rescue "N/A"%></td>
  </tr>
  <tr>
    <th>Capacity: &nbsp;</th>
    <td><%= @phone_detail.battery_capacity rescue "N/A"%></td>
  </tr>

  <tr>
    <th>Battery Technology: &nbsp;</th>
    <td><%= @phone_detail.battery_technology rescue "N/A"%></td>
  </tr>
  <tr>
    <th>Technology: &nbsp;</th>
    <td><%= @phone_detail.technology rescue "N/A"%></td>
  </tr>
  <tr>
    <th>2G: &nbsp;</th>
    <td><%= @phone_detail["2g_bands"] rescue "N/A"%></td>
  </tr>
  <tr>
    <th>3G: &nbsp;</th>
    <td><%= @phone_detail["3g_bands"] rescue "N/A"%></td>
  </tr>

  <tr>
    <th>4G: &nbsp;</th>
    <td><%= @phone_detail["4g_bands"] rescue "N/A"%></td>
  </tr>
  <tr>
    <th>GPRS: &nbsp;</th>
    <td><%= @phone_detail.gprs rescue "N/A"%></td>
  </tr>
  <tr>
    <th>EDGE: &nbsp;</th>
    <td><%= @phone_detail.edge rescue "N/A" %></td>
  </tr>
  <tr>
    <th>Announced: &nbsp;</th>
    <td><%= @phone_detail.announced rescue "N/A" %></td>
  </tr>
</table>
    
<%= link_to 'Edit', edit_phone_detail_path(@phone_detail) %> |
<%= link_to 'Back', phone_details_path %><br><br><br><br>

app/views/brands/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-lg-12">
			<h1 class="page-header">
				<%= @latest_releases.first.name %>
				<small><%= " (" + @brand.name + " latest release "  + ")"%></small>
			</h1>
		</div>
	</div>
	<div class="row">
		<a href="<%= '/phones/'+ @latest_releases.first.name.gsub(" ","_") rescue nil%>">
			<div class="col-md-8">
				<%=  File.exists?(Rails.root.to_s+"/app/assets/images/750*500/#{@brand.name.downcase}.jpg") ? image_tag("/assets/750*500/#{@brand.name.downcase}.jpg",class: "img-responsive portfolio-item",:size => "750x500") : image_tag("/assets/750*500/default2.jpg",class: "img-responsive portfolio-item",:size => "750x500") rescue image_tag("/assets/750*500/default2.jpg",class: "img-responsive portfolio-item",:size => "750x500")%>
			</div>
		</a>
		<div class="col-md-4">
			<h3>Description</h3>
			<p>
				<%#= @brand.description.present? ? @brand.description : "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae. Sed dui lorem, adipiscing in adipiscing et, interdum nec metus. Mauris ultricies, justo eu convallis placerat, felis enim." %>
				<%= @brand.name %>
			</p>
			<h3>Latest releases</h3>
			<ul>
				<% @latest_releases.each do |l_release| %>
					<li><%= l_release.name %></li>
				<% end %>
      </ul>
    </div>
  </div>
  <div class="row">
		<div class="col-lg-12">
    	<h3 class="page-header"><%= @brand.name + " Other Phones" %></h3>
    </div>
    <% @phones.each do |phone| %>
    	<div class="col-sm-3 col-xs-6">
    		<a href="<%= '/'+ @brand.name.downcase + '/' +  phone.name.gsub(" ","_").downcase %>" style="text-align: center;">
    			<%=  File.exists?(Rails.root.to_s+"/app/assets/images/420*420/#{phone.name.downcase}.jpg") ? image_tag("/assets/420*420/#{phone.name.downcase}.jpg",class: "img-responsive portfolio-item",:size => "420x420") : image_tag("/assets/420*420/default2.jpg",class: "img-responsive portfolio-item",:size => "420x420") rescue image_tag("/assets/420*420/default2.jpg",class: "img-responsive portfolio-item",:size => "420x420")%>
					<h2><strong><span style="display: inline-table;text-align: center;width:100%;"><%= phone.name %></span></strong></h2><br/>
    		</a>
			</div>
    <% end %>
  </div>  
	<!-- Code by Milind -->
	<div class="row"> 
		<% @phones.each do |phone| %>
		<div class="col-sm-6 col-md-3" style="margin-top:30px;">
			<!-- <a href="<%#= '/'+ @brand.name.downcase + '/' +  phone.name.gsub(" ","_").downcase %>"> -->
				<!-- <div class="thumbnail">  -->
					<div class="phone_image">
					<%= phone.image.present? ? (image_tag(phone.image.url,class: "img-responsive",style: "height: 212px;")) : image_tag("default.jpg",style: "height: 212px; width: 100%; display: block;") rescue nil%>
					</div>
					<div class="phone_name_tag">
						<strong><%= phone.name %></strong>
					</div>
				<!-- </div>  -->
			<!-- </a> -->
		</div> 
		<% end %> 
	</div>
</div> 

<!-- End of code -->

app/views/brands/show1.html.erb
<div class="container">
	<div class="row">
		<div class="col-lg-12">
			<h1 class="page-header">
				<%= @latest_releases.first.name %>
				<small><%= " (" + @brand.name + " latest release "  + ")"%></small>
			</h1>
		</div>
	</div>
	<div class="row">
		<a href="<%= '/phones/'+ @latest_releases.first.name.gsub(" ","_") rescue nil%>">
			<div class="col-md-8">
				<%=  File.exists?(Rails.root.to_s+"/app/assets/images/750*500/#{@brand.name.downcase}.jpg") ? image_tag("/assets/750*500/#{@brand.name.downcase}.jpg",class: "img-responsive portfolio-item",:size => "750x500") : image_tag("/assets/750*500/default2.jpg",class: "img-responsive portfolio-item",:size => "750x500") rescue image_tag("/assets/750*500/default2.jpg",class: "img-responsive portfolio-item",:size => "750x500")%>
			</div>
		</a>
		<div class="col-md-4">
			<h3>Description</h3>
			<p>
				<%= @brand.description.present? ? @brand.description : "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae. Sed dui lorem, adipiscing in adipiscing et, interdum nec metus. Mauris ultricies, justo eu convallis placerat, felis enim." %>
			</p>
			<h3>Latest releases</h3>
			<ul>
				<% @latest_releases.each do |l_release| %>
					<li><%= l_release.name %></li>
				<% end %>
      </ul>
    </div>
  </div>
  <div class="row">
		<div class="col-lg-12">
    	<h3 class="page-header"><%= @brand.name + " Other Phones" %></h3>
    </div>
    <% @phones.each do |phone| %>
    	<div class="col-sm-3 col-xs-6">
    		<a href="<%= '/'+ @brand.name.downcase + '/' +  phone.name.gsub(" ","_").downcase %>" style="text-align: center;">
    			<%=  File.exists?(Rails.root.to_s+"/app/assets/images/420*420/#{phone.name.downcase}.jpg") ? image_tag("/assets/420*420/#{phone.name.downcase}.jpg",class: "img-responsive portfolio-item",:size => "420x420") : image_tag("/assets/420*420/default2.jpg",class: "img-responsive portfolio-item",:size => "420x420") rescue image_tag("/assets/420*420/default2.jpg",class: "img-responsive portfolio-item",:size => "420x420")%>
					<h2><strong><span style="display: inline-table;text-align: center;width:100%;"><%= phone.name %></span></strong></h2><br/>
    		</a>
			</div>
    <% end %>
  </div>  
	<!-- Code by Milind -->
	<div class="row"> 
		<% @phones.each do |phone| %>
		<div class="col-sm-6 col-md-3" style="margin-top:30px;">
			<!-- <a href="<%#= '/'+ @brand.name.downcase + '/' +  phone.name.gsub(" ","_").downcase %>"> -->
				<!-- <div class="thumbnail">  -->
					<div class="phone_image">
					<%= phone.image.present? ? (image_tag(phone.image.url,class: "img-responsive",style: "height: 212px;")) : image_tag("default.jpg",style: "height: 212px; width: 100%; display: block;") rescue nil%>
					</div>
					<div class="phone_name_tag">
						<strong><%= phone.name %></strong>
					</div>
				<!-- </div>  -->
			<!-- </a> -->
		</div> 
		<% end %> 
	</div>
</div> 

<!-- End of code -->